---
  - name: This play will create new hire
    user: name={{item}} state=present group=%sudo shell=/bin/bash
    with_items: "{{newhire}}"

  - name: This will copy user ssh key credential to their .ssh directory
    authorized_key: user={{item}} key="{{lookup('file', '/data/keys/authorized_keys.{{item}}.pub')}}"
    with_items: "{{newhire}}"
